const ProductType = {
    ALL_PRODUCT_REQUEST: 'ALL_PRODUCT_REQUEST',
    ALL_PRODUCT_SUCCESS: 'ALL_PRODUCT_SUCCESS',
    ALL_PRODUCT_FAILURE: 'ALL_PRODUCT_FAILURE',
    SINGLE_PRODUCT_REQUEST: 'SINGLE_PRODUCT_REQUEST',
    SINGLE_PRODUCT_SUCCESS: 'SINGLE_PRODUCT_SUCCESS',
    SINGLE_PRODUCT_FAILURE: 'SINGLE_PRODUCT_FAILURE',
    CLEAR_ERRORS: 'CLEAR_ERRORS'
}

export default ProductType